config/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path

# pylint: disable=invalid-name
urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v1/validation/', include('wapyce.validation.api.urls')),
    path('api/v1/accessibility/', include('wapyce.accessibility.api.urls')),
    path('validation/', include('wapyce.validation.urls')),
    path('', include('wapyce.core.urls')),
]

wapyce/core/urls.py
"""
Wapyce URL Configuration for core app.
"""

from django.urls import include
from django.urls import path

from . import views

# pylint: disable=invalid-name
urlpatterns = [
    path('', views.home, name='home'),
    path('donate/', views.donate, name='donate'),
    path('account/login/', views.login, name='login'),
    path('account/logout/', views.logout_view, name='logout'),
    path('account/settings/', views.settings_view, name='settings'),
    path(
        'account/settings/new_token',
        views.new_user_token,
        name='new_user_token'
    ),
    path('oauth/', include('social_django.urls', namespace='social')),
]

wapyce/validation/api/urls.py
"""
Wapyce URL Configuration for API of validation app.
"""

from django.urls import path

from . import views

# pylint: disable=invalid-name
urlpatterns = [
    path(
        'validations/',
        views.NewValidationAPIView.as_view(),
        name='new_validation'
    ),
    path(
        'validations/<uuid:uuid>/cancel_validation/',
        views.CancelValidationAPIView.as_view(),
        name='cancel_validation'
    ),
    path(
        'validations/<uuid:uuid>/finish_validation/',
        views.FinishValidationAPIView.as_view(),
        name='finish_validation'
    ),
    path('pages/', views.NewPageAPIView.as_view(), name='new_page'),
]

wapyce/validation/urls.py
"""
Wapyce URL Configuration for validation app.
"""

from django.urls import path

from .views import ValidationDetailView
from .views import ValidationListView

# pylint: disable=invalid-name
urlpatterns = [
    path(
        'validations/',
        ValidationListView.as_view(),
        name='list_validations'
    ),
    path(
        'validations/<uuid:uuid>/',
        ValidationDetailView.as_view(),
        name='detail_validation'
    ),
]

wapyce/accessibility/models.py
"""
Models of accessibility app.
"""

from django.db import models
from django.utils.translation import gettext as _

from wapyce.core.models import CoreModel
from wapyce.validation.models import Page

# Create your models here.

class IssueCode(models.Model):
    """
    The IssueCode class is a model that represents a code of a issue of page.
    """

    code = models.CharField(
        max_length=100,
        unique=True,
        verbose_name=_('Issue code')
    )

    class Meta:
        """
        Metadata class of issue code model.
        """

        verbose_name = _('Issue code')

    def __str__(self):
        return self.code

class IssuePage(CoreModel):
    """
    The IssuePage class is a model that represents a issue of page.
    """

    ERROR = 1
    WARNING = 2
    NOTICE = 3
    TYPE_CHOICES = (
        (ERROR, _('Error')),
        (WARNING, _('Warning')),
        (NOTICE, _('Notice')),
    )

    page = models.ForeignKey(
        Page,
        on_delete=models.PROTECT,
        verbose_name=_('Page URL')
    )
    code = models.ForeignKey(
        IssueCode,
        on_delete=models.PROTECT,
        verbose_name=_('Issue code')
    )
    context = models.CharField(
        max_length=255,
        verbose_name=_('Context'),
        null=True,
        blank=True,
    )
    message = models.CharField(max_length=255, verbose_name=_('Message'))
    selector = models.CharField(
        max_length=200,
        verbose_name=_('Selector'),
        blank=True,
    )
    issue_type = models.IntegerField(
        choices=TYPE_CHOICES,
        verbose_name=_('Type')
    )

    class Meta:
        """
        Metadata class of issue model.
        """

        verbose_name = _('Issue of page')

wapyce/core/models.py
"""
Models classes inherited for models of other apps.
"""

import uuid as uuid_lib

from django.db import models
from django.utils.translation import gettext as _

# Create your models here.

class CoreModel(models.Model):
    """
    The CoreModel class is a abstract model that has common fields and methods.
    """

    uuid = models.UUIDField(
        db_index=True,
        default=uuid_lib.uuid4,
        editable=False,
        verbose_name=_('Universally unique identifier')
    )

    class Meta:
        """
        Metadata class of core model.
        """

        abstract = True

wapyce/validation/models.py
"""
Models of validation app.
"""

from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext as _

from wapyce.core.models import CoreModel
from .validators import validate_github_url

# Create your models here.

class Site(CoreModel):
    """
    The Site class is a model that represents a site that will be validated.
    """

    ACTIVE = 0
    DEACTIVATED = 1
    STATUS_CHOICES = (
        (ACTIVE, _('Active')),
        (DEACTIVATED, _('Deactivated')),
    )

    name = models.CharField(max_length=100, verbose_name=_('Name'))
    base_url = models.URLField(unique=True, verbose_name=_('Base URL'))
    github_url = models.URLField(
        unique=True,
        verbose_name=_('Github repository'),
        validators=[validate_github_url]
    )
    status = models.IntegerField(
        default=ACTIVE,
        choices=STATUS_CHOICES,
        verbose_name=_('Site status')
    )

    class Meta:
        """
        Metadata class of site model.
        """

        verbose_name = _('Site')

    def __str__(self):
        return '{} ({})'.format(self.name, self.base_url)

    @property
    def active(self):
        """
        Check that the site is active.

        :return: True if the site is active or False if not.
        :rtype: bool
        """

        return self.status == Site.ACTIVE

    @property
    def canceled(self):
        """
        Check that the site is deactivated.

        :return: True if the site is deactivated or False if not.
        :rtype: bool
        """

        return self.status == Site.DEACTIVATED

class Validation(CoreModel):
    """
    The Validation class is a model that represents a validation of site.
    """

    STARTED = 0
    CANCELED = 1
    FINISHED = 2
    STATUS_CHOICES = (
        (STARTED, _('Started')),
        (CANCELED, _('Canceled')),
        (FINISHED, _('Finished')),
    )

    site = models.ForeignKey(
        Site,
        on_delete=models.PROTECT,
        verbose_name=_('Site')
    )
    user = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        verbose_name=_('User')
    )
    start_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name=_('Start date')
    )
    end_date = models.DateTimeField(
        null=True,
        blank=True,
        verbose_name=_('End date')
    )
    status = models.IntegerField(
        default=STARTED,
        choices=STATUS_CHOICES,
        verbose_name=_('Validation status')
    )

    class Meta:
        """
        Metadata class of validation model.
        """

        verbose_name = _('Validation')

    def clean(self):
        super(Validation, self).clean()

        query = Validation.objects.filter(
            user=self.user,
            status=Validation.STARTED
        )
        if self.id:
            query = query.exclude(id=self.id)
        if query.exists():
            raise ValidationError(
                _('Already exists a validation for the same user.')
            )

    @property
    def started(self):
        """
        Check that the validation is started.

        :return: True if the validation is started or False if not.
        :rtype: bool
        """

        return self.status == Validation.STARTED

    @property
    def canceled(self):
        """
        Check that the validation is canceled.

        :return: True if the validation is canceled or False if not.
        :rtype: bool
        """

        return self.status == Validation.CANCELED

    @property
    def finished(self):
        """
        Check that the validation is finished.

        :return: True if the validation is finished or False if not.
        :rtype: bool
        """

        return self.status == Validation.FINISHED

    def cancel_validation(self):
        """
        Cancel the validation, when the user not finish the validation of all
        pages of site.
        """

        if self.started:
            self.status = Validation.CANCELED
            self.end_date = timezone.now()
            self.save()
        else:
            raise ValidationError(
                _('Only started validations can be canceled.')
            )

    def finish_validation(self):
        """
        Finish the validation, when the user validate all pages of site.
        """

        if self.started:
            if not Page.objects.filter(validation_site=self).exists():
                raise ValidationError(
                    _(
                        'The validation can be finished when at least one page'
                        + ' has validated.'
                    )
                )

            self.status = Validation.FINISHED
            self.end_date = timezone.now()
            self.save()
        else:
            raise ValidationError(
                _('Only started validations can be finished.')
            )

class Page(CoreModel):
    """
    The Page class is a model that represents a validated page of site.
    """

    validation_site = models.ForeignKey(
        Validation,
        on_delete=models.PROTECT,
        verbose_name=_('Validation')
    )
    page_url = models.URLField(verbose_name=_('Page URL'))

    class Meta:
        """
        Metadata class of validated page model.
        """

        verbose_name = _('Validated page')
        unique_together = ('validation_site', 'page_url')

    def __str__(self):
        return self.page_url

    def clean(self):
        super(Page, self).clean()

        base_url = self.validation_site.site.base_url
        if not self.page_url.startswith(base_url):
            raise ValidationError(
                _('The page URL must starts with "{}".').format(base_url)
            )

wapyce/accessibility/api/views.py
"""
Views of API accessibility application.
"""

from rest_framework.exceptions import PermissionDenied
from rest_framework.generics import CreateAPIView

from wapyce.accessibility.models import IssueCode
from wapyce.accessibility.models import IssuePage
from .serializers import IssuePageSerializer

class NewIssueAPIView(CreateAPIView):
    """
    View of API to register a new issue of page validated.
    """

    queryset = IssuePage.objects.all()
    serializer_class = IssuePageSerializer

    def perform_create(self, serializer):
        """
        Register a new issue of page validated.
        """

        validation = serializer.validated_data['page'].validation_site
        if (validation.user != self.request.user) or (not validation.started):
            raise PermissionDenied()
        code = IssueCode.objects.get_or_create(
            code=serializer.validated_data['code']
        )

        context = serializer.validated_data['context'].replace('\n', ' ')

        serializer.save(code=code[0], context=context)

wapyce/core/views.py
"""
Views of core application.
"""

from django.contrib import messages
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.shortcuts import render
from django.utils.translation import gettext as _

from rest_framework.authtoken.models import Token

# Create your views here.

def home(request):
    """
    View of home page.
    """

    return render(request, 'home.html')

def donate(request):
    """
    View of donate page.
    """

    return render(request, 'donate.html')

def login(request):
    """
    View of login page.
    """

    if request.user.is_authenticated:
        return redirect('home')
    return render(request, 'account/login.html')

def logout_view(request):
    """
    View to logout user.
    """

    logout(request)
    return redirect('home')

@login_required
def settings_view(request):
    """
    View to settings page of user.
    """

    token = Token.objects.get(user=request.user)
    return render(request, 'account/settings.html', {'user_token': token})

@login_required
def new_user_token(request):
    """
    View to generate a new token for user.
    """

    Token.objects.get(user=request.user).delete()
    Token.objects.create(user=request.user)
    messages.success(request, _('New user token created.'))
    return redirect('settings')

wapyce/validation/api/views.py
"""
Views of API validation application.
"""

from django.db.models import Q
from django.utils.translation import gettext as _

from rest_framework.exceptions import PermissionDenied
from rest_framework.exceptions import ValidationError
from rest_framework.generics import CreateAPIView
from rest_framework.generics import UpdateAPIView

from wapyce.validation.models import Site
from wapyce.validation.models import Validation
from wapyce.validation.models import Page
from .serializers import ValidationSerializer
from .serializers import PageSerializer

class NewValidationAPIView(CreateAPIView):
    """
    View of API to register the start of validation of user.
    """

    queryset = Validation.objects.all()
    serializer_class = ValidationSerializer

    def perform_create(self, serializer):
        """
        Register the start of validation of user, if they not has a validation
        started.
        """

        user = self.request.user
        query = Validation.objects.filter(user=user, status=Validation.STARTED)
        if query.exists():
            validation = query.first()
            validation.cancel_validation()

        site = Site.objects.filter(
            Q(validation__isnull=True)
            | Q(validation__status=Validation.CANCELED)
        ).filter(status=Site.ACTIVE).order_by('?').first()

        serializer.save(user=user, site=site)

class CancelValidationAPIView(UpdateAPIView):
    """
    View of API to cancel the validation of user.
    """

    queryset = Validation.objects.all()
    serializer_class = ValidationSerializer
    lookup_field = 'uuid'

    def perform_update(self, serializer):
        """
        Cancel the validation of user, if the user has a validation started.
        """

        query = Validation.objects.filter(
            user=self.request.user,
            status=Validation.STARTED
        )
        if not query.exists():
            raise ValidationError(_('The user not has a validation started.'))

        validation = query.first()
        validation.cancel_validation()
        serializer.data['end_date'] = validation.end_date
        serializer.data['status'] = validation.status

class FinishValidationAPIView(UpdateAPIView):
    """
    View of API to finish the validation of user.
    """

    queryset = Validation.objects.all()
    serializer_class = ValidationSerializer
    lookup_field = 'uuid'

    def perform_update(self, serializer):
        """
        Finish the validation of user, if the user has a validation started.
        """

        query = Validation.objects.filter(
            user=self.request.user,
            status=Validation.STARTED
        )
        if not query.exists():
            raise ValidationError(_('The user not has a validation started.'))

        validation = query.first()
        validation.finish_validation()
        serializer.data['end_date'] = validation.end_date
        serializer.data['status'] = validation.status

class NewPageAPIView(CreateAPIView):
    """
    View of API to register the page of validation of user.
    """

    queryset = Page.objects.all()
    serializer_class = PageSerializer

    def perform_create(self, serializer):
        """
        Register the page of validation of user.
        """

        validation = serializer.validated_data['validation_site']
        if (validation.user != self.request.user) or (not validation.started):
            raise PermissionDenied()
        base_url = validation.site.base_url
        page_url = serializer.validated_data['page_url']
        if not page_url.startswith(base_url):
            raise ValidationError(
                _('The page URL must starts with "{}".').format(base_url)
            )

        serializer.save()

wapyce/validation/views.py
"""
Views of validation application.
"""

from django.views.generic import DetailView
from django.views.generic import ListView

from .models import Validation

class ValidationListView(ListView):
    """
    View to list finished validations.
    """

    queryset = Validation.objects.filter(
        status=Validation.FINISHED
    ).select_related('site').select_related('user').order_by('-end_date')
    paginate_by = 20

class ValidationDetailView(DetailView):
    """
    View to detail the complete validation.
    """

    queryset = Validation.objects.filter(
        status=Validation.FINISHED
    ).select_related('site').select_related('user')
    slug_field = 'uuid'
    slug_url_kwarg = 'uuid'

wapyce/templates/validation/validation_detail.html
{% extends 'base.html' %}

{% load i18n %}
{% load l10n %}
{% load staticfiles %}

{% block title %}{% trans "Validations submited" %} - Wapyce{% endblock %}
{% block content %}
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <h2>{% trans "Validation submited" %}</h2>
    <div class="container-fluid">
      <div class="row">
        <div class="col-xs-4"><strong>{% trans "UUID" %}</strong></div>
        <div class="col-xs-8">{{ object.uuid }}</div>
      </div>
      <div class="row">
        <div class="col-xs-4"><strong>{% trans "Base URL" %}</strong></div>
        <div class="col-xs-8"><a href="{{ object.site.base_url }}" target="_blank">{{ object.site.base_url }}</a></div>
      </div>
      <div class="row">
        <div class="col-xs-4"><strong>{% trans "Github repository" %}</strong></div>
        <div class="col-xs-8"><a href="{{ object.site.github_url }}" target="_blank">{{ object.site.github_url }}</a></div>
      </div>
      <div class="row">
        <div class="col-xs-4"><strong>{% trans "User" %}</strong></div>
        <div class="col-xs-8"><a href="https://github.com/{{ object.user }}" target="_blank">{{ object.user }}</a></div>
      </div>
      <div class="row">
        <div class="col-xs-4"><strong>{% trans "Start date" %}</strong></div>
        <div class="col-xs-8">{{ object.start_date|localize }}</div>
      </div>
      <div class="row">
        <div class="col-xs-4"><strong>{% trans "End date" %}</strong></div>
        <div class="col-xs-8">{{ object.end_date|localize }}</div>
      </div>
      <div class="row">
        <div class="col-xs-4"><strong>{% trans "Validation status" %}</strong></div>
        <div class="col-xs-8">{{ object.get_status_display }}</div>
      </div>
      <div class="row">
        <div class="col-xs-12">
          <h3>{% trans "Validated pages" %}</h3>
        </div>
      </div>
      {% for page in object.page_set.all %}
      <div class="row">
        <div class="col-xs-12">
          <h4>
            {% blocktrans with page_url=page.page_url %}
              Page <small><a href="{{ page_url }}" target="_blank">{{ page_url }}</a></small>
            {% endblocktrans %}
          </h4>
          {% for issue in page.issuepage_set.all %}
          <div class="container-fluid">
            <div class="row">
              <div class="col-xs-12">
                <h5>
                  {% blocktrans with uuid=issue.uuid %}
                    Issue <small>{{ uuid }}</small>
                  {% endblocktrans %}
                </h5>
              </div>
            </div>
            <div class="row">
              <div class="col-xs-4"><strong>{% trans "Type" %}</strong></div>
              <div class="col-xs-8">{{ issue.get_issue_type_display }}</div>
            </div>
            <div class="row">
              <div class="col-xs-4"><strong>{% trans "Issue code" %}</strong></div>
              <div class="col-xs-8">{{ issue.code }}</div>
            </div>
            <div class="row">
              <div class="col-xs-4"><strong>{% trans "Message" %}</strong></div>
              <div class="col-xs-8">{{ issue.message }}</div>
            </div>
            <div class="row">
              <div class="col-xs-4"><strong>{% trans "Selector" %}</strong></div>
              <div class="col-xs-8">{{ issue.selector }}</div>
            </div>
            <div class="row">
              <div class="col-xs-4"><strong>{% trans "Context" %}</strong></div>
              <div class="col-xs-8">{{ issue.context }}</div>
            </div>
          </div>
          <hr />
          {% endfor %}
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock %}

wapyce/templates/validation/validation_list.html
{% extends 'base.html' %}

{% load i18n %}
{% load l10n %}
{% load staticfiles %}

{% block title %}{% trans "Validations submited" %} - Wapyce{% endblock %}
{% block content %}
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <h2>{% trans "Validations submited" %}</h2>
    <div class="table-responsive">
      <table class="table table-striped table-bordered table-hover">
        <thead>
          <tr>
            <th>{% trans "UUID" %}</th>
            <th>{% trans "Site" %}</th>
            <th>{% trans "User" %}</th>
            <th>{% trans "Start date" %}</th>
            <th>{% trans "End date" %}</th>
            <th>{% trans "Validation status" %}</th>
          </tr>
        </thead>
        <tbody>
          {% for validation in object_list %}
            <tr>
              <td><a href="{% url 'detail_validation' validation.uuid %}">{{ validation.uuid }}</a></td>
              <td><a href="{{ validation.site.base_url }}" target="_blank">{{ validation.site.base_url }}</a></td>
              <td><a href="https://github.com/{{ validation.user }}" target="_blank">{{ validation.user }}</a></td>
              <td>{{ validation.start_date|localize }}</td>
              <td>{{ validation.end_date|localize }}</td>
              <td>{{ validation.get_status_display }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    {% if is_paginated %}
      <div class="pagination">
        <nav aria-label="Page navigation">
          <ul class="pagination">
            {% if page_obj.has_previous %}
              <li>
                <a href="{% url 'list_validations' %}?page={{ page_obj.previous_page_number }}" aria-label="{% trans 'Previous' %}">
                  <span aria-hidden="true">&laquo;</span>
                </a>
              </li>
            {% else %}
              <li class="disabled">
                <span><span aria-hidden="true">&laquo;</span></span>
              </li>
            {% endif %}
            {% with ''|center:page_obj.paginator.num_pages as range %}
              {% for _ in range %}
                {% if page_obj.number == forloop.counter %}
                  <li class="active"><span>{{ forloop.counter }} <span class="sr-only">({% trans "current" %})</span></span></li>
                {% else %}
                  <li><a href="{% url 'list_validations' %}?page={{ forloop.counter }}">{{ forloop.counter }}</a></li>
                {% endif %}
              {% endfor %}
            {% endwith %}
            {% if page_obj.has_next %}
              <li>
                <a href="{% url 'list_validations' %}?page={{ page_obj.next_page_number }}" aria-label="{% trans 'Next' %}">
                  <span aria-hidden="true">&raquo;</span>
                </a>
              </li>
            {% else %}
              <li class="disabled">
                <span><span aria-hidden="true">&raquo;</span></span>
              </li>
            {% endif %}
          </ul>
        </nav>
      </div>
    {% endif %}
  </div>
</div>
{% endblock %}